---
title: "FFORMA: Feature-based Forecast Model Averaging"
author:
- familyname: Montero-Manso
  othernames: Pablo
  address: Department of Mathematics, University of A Coruña, Spain
  email: p.montero.manso@udc.es
  correspondingauthor: true
- familyname: Athanasopoulos
  othernames: George
  address: Department of Econometrics and Business Statistics, Monash University, Australia
  email: george.athanasopoulos@monash.edu
- familyname: Hyndman
  othernames: Rob J
  address: Department of Econometrics and Business Statistics, Monash University, Australia
  email: rob.hyndman@monash.edu
- familyname: Talagala
  othernames: Thiyanga S
  address: Department of Econometrics and Business Statistics, Monash University, Australia
  email: thiyanga.talagala@monash.edu
abstract: We propose an automated method for obtaining weighted forecast combinations using time series features. The proposed approach involves two phases. First, we use a collection of time series to train a meta-model to assign weights to various possible forecasting methods with the goal of minimizing the average forecasting error obtained from a weighted forecast combination. The inputs to the meta-model are features extracted from each series. In the second phase, we forecast new series using a weighted forecast combination where the weights are obtained from our previously trained meta-model. Our method outperforms a simple forecast combination, and outperforms all of the most popular individual methods in the time series forecasting literature. The approach achieved second position in the M4 Competition.
keywords: Time series features, Forecast combination, XGBoost, M4 Competition, Meta-learning
wpnumber: no/yr
jelcodes: C10,C14,C22
blind: true
cover: false
toc: false
bibliography: references.bib
biblio-style: authoryear-comp
output:
  MonashEBSTemplates::workingpaper:
    fig_caption: yes
    fig_height: 5
    fig_width: 8
    includes:
      in_header: preamble.tex
    keep_tex: yes
    number_sections: yes
    citation_package: biblatex
---

\lfoot{}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache=TRUE, messages=FALSE, warning=FALSE)
# Make sure you have the latest version of rmarkdown and bookdown
#devtools::install_github("rstudio/rmarkdown")
#devtools::install_github("rstudio/bookdown")
library(ggplot2)
```
<!-- OLD ABSTRACT: It is well known that ensemble approaches produce improvements over single methods in statistical learning. Nevertheless, when calculating predictions over a large dataset, computation time for the whole ensemble can be prohibitive, so individual model selection becomes the preferred approach. We present a method for combining forecasting models by posing it as a classification problem using features extracted from the time series. Unlike regular classification problems, we minimize the average forecast error of the selected method rather than the classification error. Not only does this address the aim of accurate forecasting, it also provides measures of relative method accuracy across the time series, and relative difficulty across time series. In contrast, a classic classification approach would give the same importance to all series and methods. The presented classifier is compared with state-of-the-art approaches to forecasting and time series classification. The results show an improvement of error over alternative approaches. These experiments allow us to show the relevance of both the feature set and the proposed optimization approach to several collections of time series. The scalability of the approach allows it to be applied to forecasting a large collection of time series. It can also be efficiently trained to tailor specific domains or datasets. -->


# Introduction {#intro}

There are essentially two general approaches for forecasting a time series: (i) generating forecasts from a single model, and (ii) combining forecasts from many models or forecast model averaging. There has been a vast literature on the latter motivated by the seminal work of @Bates1969-cu and followed by a plethora of empirical applications showing that combination forecasts are often superior to their individual counterparts [see among others, @Cle1989 \textcolor{red}{maybe add more here}]. Combining forecasts is considered a successful way of hedging against the risk of selecting a misspecified model. Of course the main challenge is in selecting an appropriate set of weights with many contributions [see for example, @Aiolfi2011-yz] attempting to overcome the so called ``forecast combination puzzle''.

There have been various efforts in the literature using time series features combined with meta-learning for forecasting [see for example @prudencio2004using; @LEMKE20102006; @KucEtAl2016]. \textcolor{red}{(Leave this for Rob as a reminder: not sure how to include Kang et a. 2017 here).} Recently @fforms proposed FFORMS (Feature-based FORecast Model Selection) a framework that focuses on using time series features combined with meta-learning for forecast-model selection. In this paper we build on this framework posing the learning problem in a way that includes information about the forecast errors produced by the set of candidate forecasting methods and combines these with features extracted from the time series in order to derive a set of weights for forecast combinations. We label this framework, FFORMA (Feature-based FORecast Model Averaging). FFORMA resulted in the second most accurate point forecasts and prediction intervals amongst all competitors in the M4 competition.

The rest of the paper is organized as follows: In \autoref{methodology} we describe the FFORMA framework in a very general sense. \autoref{M4application} gives the details of our implementation of FFORMA in the M4 Competition for generating both point and interval forecasts. This includes the required preprocessing steps, the set of features and forecast methods, as well as the specific implementation of the meta-learning model. We show empirical evidence on the performance of the approach in \autoref{results} by quantifying the difference between our proposed learning model and a traditional classifier approach. \autoref{conclusion}  provides some final remarks and conclusions.

# Methodology {#methodology}

## Intuition and overview of FFORMA

The objective of our meta-learning approach is to derive a set of weights to combine forecasts generated from a *pool of methods* (e.g., \naive, exponential smoothing, ARIMA, etc.). The FFORMA framework requires a set of time series we refer to as the *reference set*. From these the algorithm learns in order to produce forecast combination weights for any given time series. Each time series in the reference set is divided into a training period and a test period. From the training period a set of *time series features* are calculated (e.g., length of time series, strength of trend, etc.). These form the inputs for training the meta-learning model. Moreover, each method in the pool is fitted to the training period and forecasts are generated over the test period. From these, *forecast errors* are computed for each method which form the supervised part for the training of the meta-learning model. These are subsequently summarised using a forecast error measure.

<!--The forecasting errors of each method in the pool are calculated for each time series in the reference set, using the true future values of the series if available or by dividing the each series into a training period and test period by applying temporal holdout.-->

The meta-learning model learns to produce weights for each method in the pool as a function of the features of the series to be forecasted. Once the model is trained, the inductive step consists of assuming that a new series for which forecasts are required comes from a *generating process* similar to the one that generated the reference set.

A common meta-learning approach is to learn to select the best method in the pool of methods for each series, i.e., the one that produces the smallest forecast error. This approach transforms the problem into a traditional classification problem by setting the individual forecasting methods as the classes and the best method as the target class for each time series. However, this simplification removes relevant information which may be useful in the meta-learning process, such as, which methods produce similar errors to the most accurate one, or which series are the most difficult to forecast and hence have more impact in the total forecast error. In this paper we do not apply this simplification but instead take into account the exact error that each method produces. This information is introduced into the model by posing the problem as finding a function that assigns *probabilities* to each forecasting method, with the objective of minimizing the expected error that would have been produced if the methods were picked at random following these probabilities. This approach is more general than classification, and can be thought of as classification  with *per class weights* (the forecast errors) that vary per instance, combined with *per instance weights* that assign more importance to some series.


<!-- The meta-learning process can therefore be summarized the following way: -->

<!--   * $X_i$ the $i$-eth series on the regerence set. -->
<!--   * $e_{ij}$ the error the individual forecasting method $j$ makes on series $i$. -->
<!--   * $x_{i}$ the feature vector extracted from series $X_i$. -->
<!--   * $f$ is a function belonging to a hypothesis space $H$ (such as linear functions) that maps features to probabilities, such as $f(x)_j$ is the probabilitie assigned to the $j$-eth method in the pool. -->

<!-- $$ argmin_{f \in H} \sum_i \sum_j f(x_{i})_je_{ij} $$ -->


<!--  Given a new time series, a trained meta-learning algorithm produces probabilities for each of the forecasting methods considered in the pool. The final forecast can be computed from these probabilities in two-ways: -->

<!--  1. A weighted average of the individual forecast methods. -->
<!--  This tends to produce the best forecast on average, but requires computing the forecasts of all methods in out pool, which may be time consuming. -->
<!--  2. Selecting the method with the largest probability. This prevents the need to calculate all the forecast of the individual methods in our pool, but produces less acurate forecasts on average. -->

## Algorithmic description

The operation of the FFORMA framework comprises two phases: (i) the offline phase, in which we train a meta-learner and (ii) the online phase, in which we use the pre-trained meta-learner to identify forecast combination weights. Algorithm \@ref(alg:algo-lab) presents in detail the Pseudo code of the proposed framework.

<!--
  1. The set of forecasting methods, the pool of methods.
  2. The set of features to be extracted from the time series
  3. A training set of time series, the reference set.
  4. The forecasting error measure, such as mean squared error.

The FFORMA framework works in two phases: an **offline** phase, when the meta-learned is trained and an **online** phase, when forecasts are produced.  describes the two phases. -->


\begin{algorithm}[!ht]
  \caption{The FFORMA framework - Forecast combination based on meta-learning. }
  \label{alg:algo-lab}
  \begin{algorithmic}[1]
    \Statex \textbf{Offline phase - train the learning model}
    \Statex \text{Inputs:}
    \Statex \hspace{1cm}$\{x_1, x_2, \dots,x_N\}:$ $N$ observed time series forming the reference set.
         \Statex \hspace{1cm}$F:$ a set of functions for calculating time series features.
         \Statex \hspace{1cm}$M:$ a set of forecasting methods in the pool, e.g., \naive, ETS, ARIMA, etc.
           \Statex \hspace{1cm}$K:$ number of iterations in the xgboost algorithm.
     \Statex \text{Output:}
      \Statex \hspace{1cm}\text{FFORMA meta-learner: A function from the extracted features to a set of $M$}
      \Statex \text{\hspace{1cm} probabilities, one for each forecasting method.}\vspace{0.3cm}
    \Statex \textit{Prepare the meta-data} \vspace{0.1cm}
    \Statex For $n=1$ to $N$:
            \State Split $x_n$ into a training period and test period.
            \State Calculate the set of features $\bm{f}_n\in F$ over the training period.
            \State Fit each forecasting method $m\in M$ over the training period and generate forecasts over the test period.
            \State Calculate forecast losses $L_{nm}$ over the test period.
    \State Meta-data: input features $\bm{f}_n$ (Step 2), output loss $L_{nm}$ (Step 4).
     \Statex
    \Statex \textit{Train the meta-learner, $w$}  \vspace{0.1cm}
            \State Train a learning model based on the meta-data and errors, by minimizing:
            $$ argmin_w \sum_{n=1}^N \sum_{m=1}^M w(\bm{f}_n)_{m} L_{nm}$$ were $L$ is the loss function.
    \Statex
     \Statex \textbf{Online phase - forecast a new time series}
    \Statex \text{Input:}
    \Statex \hspace{1cm}\text{FFORMA classifier from Step 6}.
     \Statex \text{Output:}
      \Statex \hspace{1cm}\text{Forecast the new time series $x_{new}$}.
      \Statex For $x_{new}$:
  \State Calculate features $\bm{f}_{new}$ by applying $F$.
  \State Use the meta-learner to produce $\bm{w}(\bm{f}_{new})$ an $M$-vector of probabilities.
  \State Compute the individual forecasts of the $M$ forecasting methods in the pool.
  \State Combine individual forecasts using $\bm{w}$ to generate final forecasts.
   \end{algorithmic}

\end{algorithm}


<!-- The algorithm produces weights for each forecasting method. These weights can also be interpreted as the probability of each method being best. These weights can be used either to select the "best" forecasting method for each series or to combine the forecasts using weighted linear combination. Note that the accuracy of the FFORMA meta-learner depends on three main factors: -->

<!--   1. Forecasting methods used in the pool -->
<!--   2. The set of time series features we considered -->
<!--   3. The collection of time series used to train the classifier. -->

<!--   Section 3 provides a more detailed description of application of the FFORMA framework over the course of M4 competition.  -->

\clearpage

#Implementation and Application to M4 Competition {#M4application}


## Reference set

The M4 dataset includes 100,000 real-world time series of yearly, quarterly, monthly, weekly, daily and hourly data. All 100,000 series form the reference set. Each series is split into training period and a test period. The length of the test period for each time series was set to be equal to the forecast horizon set by the competition. When the resulting training period was too short (fewer than two observations \textcolor{red}{I have left this as observations to avoid confusion with train and test period} \textcolor{green}{ok, also it is not a very important detail, we can remove the whole sentence.}), the size of the test period was reduced. The series that were simply a constant over the training period were eliminated from any further analysis.

## Time series features

\autoref{feature} provides a brief description of the features used in this experiment, $F$ in Algorithm \@ref(alg:algo-lab). The functions to calculate these are implemented in the `tsfeatures` R package by @tsfeatures. Most of the features (or variations of these) have been previously used in a forecasting context by @hyndman2015large and @fforms (please refer to these papers for detailed descriptions). The ARCH.LM statistic is calculated based on the Lagrange Multiplier test of @engle1982autoregressive for autoregressive conditional heteroscedasticity (ARCH). For the heterogeneity features 39-42, the time series is first pre-whitened using an AR model resulting to a new series $z$. A GARCH(1, 1) model is then fitted to the pre-whitened series to obtain the residual series, $r$. Subsequently, the features are computed.

Features corresponding to seasonal time series only, are set to zero for the case of non-seasonal time series. Note that for the sake of generality, we have not used any of the domain-specific features such as macro, micro, finance, etc., even though this information was available in the M4 data set.

<!--No exogenous features were used, even though they were available in the M4 dataset, such as which domain the series belongs to (e.g. macroeconomics, finance, tourism...).-->

\begin{table}[!htp]
\centering\footnotesize\tabcolsep=0.12cm
\caption{Features used in FFORMA framework.}
\label{feature}
\begin{tabular}{llp{8,8cm}cc}
\toprule
\multicolumn{2}{c}{Feature} & Description & Non-seasonal & Seasonal\\
\midrule
1  & T              & length of time series                                                                   & \yes  & \yes \\
2  & trend          & strength of trend                                                                       & \yes  & \yes\\
3  & seasonality    & strength of seasonality                                                                 & -     & \yes \\
4  & linearity      & linearity                                                                               & \yes  & \yes \\
5  & curvature      & curvature                                                                               & \yes  & \yes \\
6  & spikiness      & spikiness                                                                               & \yes  & \yes \\
7  & e\_acf1        & first ACF value of remainder series                                                     & \yes  & \yes \\
8  & e\_acf10       & sum of squares of first 10 ACF values of remainder series                                                    & \yes  & \yes \\
9  & stability      & stability                                                                               & \yes  & \yes \\
10  & lumpiness      & lumpiness                                                                               & \yes  & \yes \\
11 & entropy        & spectral entropy                                                                        & \yes  & \yes \\
12 & hurst          & Hurst exponent                                                                          & \yes  & \yes \\
13 & nonlinearity   & nonlinearity                                                                            & \yes\ & \yes \\
13 & alpha          & ETS(A,A,N) $\hat\alpha$                                                                 & \yes  & \yes \\
14 & beta           & ETS(A,A,N) $\hat\beta$                                                                  & \yes  & \yes\\
15 & hwalpha        & ETS(A,A,A) $\hat\alpha$                                                                 & -     & \yes \\
16 & hwbeta         & ETS(A,A,A) $\hat\beta$                                                                  & -     & \yes \\
17 & hwgamma        & ETS(A,A,A) $\hat\gamma$                                                                 & -     & \yes \\
18 & ur\_pp         & test statistic based on Phillips-Perron test                                            & \yes  & \yes \\
19 & ur\_kpss       & test statistic based on KPSS test                                                       & \yes  & \yes \\
20 & y\_acf1        & first ACF value of the original series                                                  & \yes  & \yes \\
21 & diff1y\_acf1   & first ACF value of the differenced series                                               & \yes  & \yes \\
22 & diff2y\_acf1   & first ACF value of the twice-differenced series                                         & \yes  & \yes \\
23 & y\_acf10        & sum of squares of first 10 ACF values of original series                                 & \yes  & \yes \\
24 & diff1y\_acf10   & sum of squares of first 10 ACF values of differenced series                              & \yes  & \yes \\
25 & diff2y\_acf10   & sum of squares of first 10 ACF values of twice-differenced series                        & \yes  & \yes \\
26 & seas\_acf1     & autocorrelation coefficient at first seasonal lag                                       & -     & \yes \\
27 & sediff\_acf1   & first ACF value of seasonally-differenced series                                        & -     & \yes\\
28 & y\_pacf5       & sum of squares of first 5 PACF values of original series                                & \yes  & \yes \\
29 & diff1y\_pacf5  & sum of squares of first 5 PACF values of differenced series                             & \yes  & \yes \\
30 & diff2y\_pacf5  & sum of squares of first 5 PACF values of twice-differenced series                       & \yes  & \yes \\
31 & seas\_pacf  & partial autocorrelation coefficient at first seasonal lag                       & \yes  & \yes \\
32 & crossing\_point  & number of times the time series crosses the median                     & \yes  & \yes \\
33 & flat\_spots  & number of flat spots, calculated by discretizing the series into 10 equal sized intervals and counting the maximum run length within any single interval                       & \yes  & \yes \\
34 & nperiods  & number of seasonal periods in the series & -  & \yes \\
35 & seasonal\_period  & length of seasonal period                       & -  & \yes \\
36 & peak  & strength of peak                      & \yes  & \yes \\
37 & trough  & strength of trough                      & \yes  & \yes \\
38 & ARCH.LM  & ARCH LM statistic                      & \yes  & \yes \\
39 & arch\_acf  &    sum of squares of the first 12 autocorrelations of $z^2$               & \yes  & \yes \\
40 & garch\_acf  &  sum of squares of the first 12 autocorrelations of $r^2$                 & \yes  & \yes \\
41 & arch\_r2  &     $R^2$ value of an AR model applied to $z^2$              & \yes  & \yes \\
42 & garch\_r2  &   $R^2$ value of an AR model applied to \textcolor{blue}{$r^2$}               & \yes  & \yes \\
\bottomrule
 \end{tabular}
\end{table}

\clearpage

## Pool of forecasting methods

We consider nine methods implemented in the `forecast` package in R [@forecast] for the pool of methods, $P$ in Algorithm \@ref(alg:algo-lab). They are (the specific R calls for fitting the models are given):

i. \naive\ (`naive`);
i. random walk with drift (`rwf` with drift=TRUE);
i. seasonal \naive\ (`snaive`).
i. theta method (`thetaf`);
i. automated ARIMA algorithm (`auto.arima`);
i. automated exponential smoothing algorithm (`ets`);
i. TBATS model (`tbats`);
i. STLM-AR Seasonal and Trend decomposition using Loess with AR modeling of the seasonally adjusted series (`stlm` with model function `ar`);

In all cases, the default settings are used. Further, in the case of an error when fitting the series (e.g. a series is constant), the `snaive` forecast method is used instead.

<!--It is worthy to emphasize that we used the default parameters in most methods without any hand tunning. Only in `auto.arima` we specified a more thorough search for hyperparameters than its default version.-->

## Forecast error measure

\textcolor{red}{We don't need this at all as we stipulate the $L$  below. Let's remove this.}

\textcolor{green}{We can remove the whole section, there is only one small detail:
The OWA is defined in the guide as a measure for the whole dataset, what we use in FFORMA is the *contribution* to the OWA of each series.
Added the clarification in $L$ below. Do you think is enough?
Also, I think the OWA as written in the in the M4 guide *may* not be very clear, personally, I ended up going to the source code they provided.
}

The forecasting error measure, $E$ in Algorithm \@ref(alg:algo-lab), is adapted from the Overall Weighted Average error described in the M4 competitor's guide @M4compguide, which adds together the Mean Absolute Scaled Error and the symmetric Mean Absolute Percentage Error. For each series and method, the Mean Absolute Scaled Error and the symmetric Mean Absolute Percentage Error are divided by the respective error of the Naive 2 method *over all series in the dataset* (i.e. MASE by the average MASE of Naive 2), and then added.


## Metal-learning model implementation

We use the gradient tree boosting model of `xgboost` as the underlying implementation of the learning model.  This is a state of the art computationally efficient model that has shown good performance in structure based problems [@chen2016xgboost]. The great advantage here is that we are able to customise the model to fit our objective function.

### The xgboost objective function

The basic xgboost algorithm produces numeric values from the features, one for each forecasting method in our pool. We apply the softmax transform to these values prior to computing the the objective function which includes the forecasting errors shown in Algorithm \@ref(alg:algo-lab) Step 6. This implemented as a *custom objective function* in the xgboost framework.

xgboost requires a gradient and hessian of the objective function to fit the model. The *correct* hessian is prone to numerical problems that need to be addressed for the boosting to converge. This is a relative common problem and one simple fix is to use an upper bound of the hessian by clamping its small values to a larger one. We computed a different upper bound of the hessian by removing some terms from the correct hessian. Although both alternatives converge, the later works faster, requiring less boosting steps to converge. This not only increases the computational efficiency, it also generalizes better due to a less complex set of trees produced in the final solution. \textcolor{red}{I am not sure about the above. I leave to Rob to evaluate.}

The  general paremeters of the meta-learning in Algorithm \@ref(alg:algo-lab) are set to:


  * $p(\bm{f}_n)_m$ is the output of the xgboost algorithm, one value for each forecasting method m, for the features extracted from series $x_n$.
  * $w(\bm{f}_n)_{m} = \frac{exp(p(\bm{f}_n)_m)}{ \sum_m exp(p(\bm{f}_j)_m)}$ is the transformation to probabilities of the xgboost output by applying the softmax transform.
  * $L_{nm}$ is the contribution to the OWA error measure of method m for the series n. OWA is defined in the M4 Competitor's Guide @M4compguide.
  * $\bar{L}_n = \sum_{m=1}^M w(\bm{f}_n)_m L_{nm}$ is the weighted average loss function, Step 6 of Algorithm \@ref(alg:algo-lab).
  * \textcolor{red}{I am not sure at all how the following two are derived. Rob was not sure either. Pablo can you please help us understand here.} $G_{nm} = \frac{\partial{\bar{L}_n}}{\partial{p(\bm{f}_n)_m}} = w_{nm}(L_{nm} - \bar{L}_n)$ is the gradient of the loss function. \textcolor{green}{!!The denominator of the derivative was incorrect. I wanted to show the gradient with respect to the xgboost prediction, $p$, not after the softmax transform, $w$ (which is only added because it is very convenient notation-wise).
  \\The formula is written in a way that is computationally efficient, in "vector form" and to reuse many terms, maybe that is why it is not straightforward.
  \\ NOTATION WISE, Do you think it is OK or should we use
  $\frac{\partial{\bar{L}_n}}{\partial{p_n}}$}
  * The hessian $H_{nm}$ is approximated by our upper bound $\hat{H}_{nm}$:
  $$ H_{nm} = \frac{\partial{G_n}}{\partial{p(\bm{f}_n)_m}} \approx \hat{H}_n = w_n(L_n(1-w_n) - G_n)  $$

The functions $G$ and $\hat{H}$ are passed to the xgboost algorithm to minimize our objective function $L$.

### Hyperparameters

 The results of xgboost  are particularly dependent on its hyper-parameters such as learning rate, number of boosting steps, maximum complexity allowed for the trees or subsampling sizes. We limit the hyper-parameter search space based on some initial results and rules of thumb and explore it using Bayesian optimization [implemented in the `rBayesianOptimization` R package @rBayesianOptimization] measuring performance on a 10% holdout version of the reference set. We picked the simplest hyper-parameter set from the top solutions of the exploration.

## Prediction Intervals

For each series $x_{new}$ we use as the center of the interval the point forecast produced by our meta-learner. Then the 95% bounds of the interval are generated by a linear combination of the bounds of three forecasting methods: \naive, theta and seasonal \naive\ . The coefficients for the linear combination are calculated in a data driven way over the M4 database. The complete  procedure is as follows:

1. We divide the M4 dataset into two parts: A and B. We train the FFORMA learner using the training periods of the series in part A and produce point forecasts over the \textcolor{green}{training periods of the} series of part B, and vice versa.

2. We compute the 95% *predicion radius* for the \naive, theta, and seasonal \naive\ methods. This is the difference between the 95% upper bound and the point forecast for each forecast horizon.

3. For each forecast horizon we find the coefficients that minimize the MSIS of the interval, as defined in the M4 Competitor's guide @M4compguide, with the FFORMA point forecast as the center and a linear combination of the radiuses of \naive, theta, seasonal \naive\ forecasts as the interval. The minimization is done by gradient descent over the test period of the series.

This method produces a set of three coefficients for each prediction horizon in the M4 dataset and these coefficients will be the same independently of the series we want to forecast. Unlike the point forecast, these coefficients are not restricted to be probabilities.


# Results{#results}

In order to evaluate the impact of our contribution we compared the average forecast error produced by FFORMA with a *model selection* approach.

In model selection meta-learning, a classifier is trained to predict the "best method" for each series based on the features instead the FFORMA scheme of producing probabilities to minimize overall OWA. The final forecasts are the ones produced by method in the pool predicted by the classifier to be the best, not by averaging.

All other implementation details are kept the same as in FFORMA, specifically it uses the same set of features, the same pool of forecasting methods, the same underlying implementation (xgboost) and the same hyperparameter search.  This enables to measure the impact of the FFORMA original loss function, with a "model selection approach", all other things being equal.

We applied both FFORMA and the *model selection approach* to the M4 dataset and compared their overall point forecast errors. The error of the FFORMA approach is 10\% smaller than model selection, measured as $\frac{model\ selection\ OWA}{FFORMA \ OWA}$.
\textcolor{green}{SECTION HAS BEEN REWRITTEN}
\textcolor{red}{Pablo can you elaborate a little here. A couple more sentences shoud be enough. It is not exactly clear to me what this does. What you have on the comments below are very interesting and I think really worth writing up in order to understand/evaluate FFORMA. I think it would really be worth putting all this work in a seprate paper. I cannot see why the IJF would not be interested in it.}

<!--
#classif 0.8566705
#our combi 0.7770559

 Maybe we can show here results about the metalearning, how weights evolve with series length. What is the difference between weightedaveraging and selection in our model? What happens if we remove individual forecasting methods? How robust are we against this? wHich features are more important? -->

# Discussion and Conclusions{#conclusion}

We have presented an algorithm for forecasting using weighted averaging of a set of models. The objective function of the learning model assigns probabilities to forecasting methods in order to minimize the forecasting error that would be produced if we picked the methods at random using these probabilities. This contrasts with how the final forecasts are produced, which is a weighted average, not a selection. These weights can however be used as model selection algorithm, if one picks the methods receiving the largest weight. This can be useful for interpretability or computational reasons, at the cost of forecasting performance.

One advantage of the approach is that its form is not independent of the forecasting error measure. Forecasting errors enter the model as additional precalculated constants. This allows FFORMA to adapt to arbitrary error measures when models that directly minimize them would be restricted, e.g. our approach can be applied to non-differentiable errors.

We explored minimizing the weighted average of the forecasts, but the results did not improve over the simple version.

The source code for FFORMA is available at \url{https://github.com/robjhyndman/M4metalearning}.

<!-- \textcolor{blue}{Fotios email: We would like, though, to see a short section that discusses the reasons behind the good performance of your method. } -->

<!-- ##Reasons behind the performance -->

<!--   1. As opposed to individual methods in our pool, it is being trained to the specific error in the M4 Competition. The methods in our pool do not minimize the OWA error, but the squared loss, while we generated probabilities based on the OWA error. -->
<!--   0. As opposed to individual selection methods, it exploits domain bias. -->
<!--    One method could be discarded in a series when the error is low, because on average it performs bad in the rest of the dataset, while individual methods would pick it up. " -->
<!--    3. Exploiting dependencies between time series. In the M4 competition, some time series are similar, which can be hypothesized as macroeconomic indicators of neighbouring countries, etc. This effect is explited in the metalearning model and the series would produce similar features, and the errors that the model minimizes are more accurate. -->
<!--    2. AS opossed to traditional classification meta-learning approaches: Take the individual errors into account. This works two ways, capturing similarity the results in methods to keep the model simple (. Capturing differences in time series to keep the model simple (difficult do not end up affecting the model much). -->
<!--   4. Compared to a naive averaging of individual methods, it exploits easily discardable methods. Many ensemble approaches work by averaging the output of individual methods. This is especially when the number of individual forecasting methods grows and allows us to include methods with radically different assumptions that would not be appropiate to average. e.g."for really short time series you really cant do better than naive, others just overfit" -->
<!--   5. As opposed to just holdout crossvalidation, our method performs better. If we allow the method to overfit, i will reproduce the results of the holddout crossvaliation error, but in our case it improves it. -->
<!--   6. Bias variance tradeoff - Picking best method has high variance, by using the relative errors we reduce it. -->
<!--   7. EXPERIMENT: Train with few data and see what happens. -->
<!--   8. EXPERIMENT: compared against a traditional classifier approach with xgboost -->
<!--  - Features importance, evolution of weights according to some features. -->
<!-- E.G. "we can see that our meta learning approaches successfully captures the preference of X method against Y method when the strength of the trend grows, (compared to the true preference using the test set)". -->
<!--   - Comparison of performance of meta-learning against crossvalidation error. -->
<!-- E.G "our method outperforms model selection using crossvalidation, showing the successful exploitation of the domain information" -->
<!--  - Robustness against removing features, removing methods in the pool. -->
<!-- E.G. "The meta-learning approach is robust against changes in the pool of methods and feature set, showing that they are not spurious results..." -->
<!--  - Performance of Selection vs Averaging using our weights -->
<!-- E.G "The relative loss of accuracy if we want to perform model selection instead of averaging with our model". -->
<!-- -Performance compared to naive averaging, or how much the weights deviate from equal weights, to give a sense of the impact of the meta learning. -->
<!-- These need no to overlap with the general M4 paper, i.e. we are not discussing the performance of our method in weekly or monthly series and other results that I suppose they will talk about, and we only mention accuracy in a relative sense. -->
<!-- I will write some draft and then we can edit from there. -->

# References